# Header
menu:
  首页: natsuneko3.github.io
  友链: https://www.realtime.xyz/
  关于: /about

# 主页banner图
banner: https://w.wallhaven.cc/full/6o/wallhaven-6o55ml.jpg

# 站点通知信息
notice: 

# 作者信息
author:
  name: 夏猫(Natsuneko)
  avatar: https://w.wallhaven.cc/full/lm/wallhaven-lmljgl.png
  description: 这是一个小小的个人网站，到时候会自己开个网站，这里主要会写一点ue文章和插件，后续会加点有趣的东西？

toc:
  max_depth: 3 # 生成 TOC 的最大深度
  min_depth: 2 # 生成 TOC 的最小深度

comments:
  enable: false
  use: 'valine' # valine || disqus
  # valine 评论
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  # 这里appId和appKey一定一定要改成自己的，没有的话去https://leancloud.cn这个网站注册创建一个
  valine:
    appId: 
    appKey: 
    avatar: mm
    placeholder: 随便说点什么叭～
    notify: true
    visitor: true
    pageSize: 10
  # disqus 评论
  # docs: https://disqus.com/
  disqus:
    website: 
    error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# mathjax LaTeX公式支持
#docs: http://docs.mathjax.org/en/latest/
mathjax:
    enable: true

# 国内备案信息
beian: 

# 谷歌分析
google_analytics: 
# gauges分析
gauges_analytics: 
# 百度分析
baidu_analytics: 
# 腾讯分析
tencent_analytics: 
# 站点ico
favicon: /favicon.ico


# Social Icon
social_icon:
  enable: true
  icons:
    ins     :
    zhihu   : https://www.zhihu.com/people/Natsuneko
    weibo   : 
    github  : https://github.com/Natsuneko3/
    twitter : https://twitter.com/natsunekosan